# Generated by Django 3.0.6 on 2020-06-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
